#!/bin/sh
DF_DIR=$(dirname "$0")
cd "${DF_DIR}"
export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
#export SDL_VIDEO_CENTERED=1 # Centre the screen.  Messes up resizing.

# >>> LNP modification:

#apply any ARCH/distro fixes
. "./distro_fixes.sh" "${DF_DIR}"
LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}$PRELOAD_LIB" "./libs/Dwarf_Fortress" "$@" # Go, go, go! :)
exit $?

# <<< LNP modification:

./libs/Dwarf_Fortress "$@" # Go, go, go! :)
